version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dmz"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "ci"
    groups:
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/basic-nextjs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/basic-nextjs-pages-router"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/basic-spa"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/kit-nextjs-skate-park"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/kit-nextjs-article-starter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/kit-nextjs-location-finder"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/examples/kit-nextjs-product-listing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "security"
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
